### PR TITLE
Fix emscripten compilation

### PR DESCRIPTION
**Pull request by bchapuis**
Really nice project; everything has gone smoothly so far. I had to make a couple of modifications to ensure the examples compile and run in the browser (maybe this can be addressed with a parameter instead, but I'm not a cmake expert). I also added a GitHub Actions step that I haven't been able to test, as the actions are not triggered in PRs. Hope this helps.

Best regards,

Bertil

### CODE REVIEW

**Comment by markaren** [comment]
I kinda assume that the extra `../` is due to where the binaries are located on your system vs mine. The solution would be to fix this in the CMake config.

`set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin)` was supposed to this but apparantly not.

```cpp
        #ifndef __EMSCRIPTEN__
        // Only run this on desktop OpenGL, not in WebGL
        glGetTexImage(GL_TEXTURE_2D, 0, gl::toGLFormat(texture.format), gl::toGLType(texture.type), data.data());
        #endif
```

I have not had any issues with this, are you saying it has no effect?

**Comment by markaren** [comment]
I think it is best to keep this PR to the CI change and potentially the GLRenderer change. The paths needs another type of change.

**Comment by markaren** [comment]
For some reason I thought I had to use relative paths for emscripten files, but seems I don't. So I will push a change for that.

**Comment by bchapuis** [comment]
Cool, I reverted the changes to the CMakeList.txt files and moved the glGetTexImage in a dedicated commit so you can cherry pick what you need. As said, I havn't been able to test the CI job, but it would be nice to have one for emscripten.

**Comment by markaren** [comment]
I were going to make some changes to this PR, but I see that the PR is coming from your master branch.

Would you mind closing this PR, make a new one in a new branch based off dev?

**Comment by bchapuis** [comment]
I didn't notice the dev branch. I just rebased in this PR, Is this sufficient?

**Comment by markaren** [comment]
Your master branch will diverge from upstream, but ok for me.

**Comment by markaren** [comment]
You can test these changes, and I need to figure out how to make the CI run. Or I can just merge to dev first. We'll see later

**Comment by bchapuis** [comment]
Cool, the emscripten compilation went well on my mac.

**Comment by markaren** [comment]
`-DCMAKE_TOOLCHAIN_FILE=${{env.EM_CACHE_FOLDER}}/libexec/cmake/Modules/Platform/Emscripten.cmake` does not seem to be correct.

**Comment by markaren** [comment]
This works:

```yml
  linux-emscripten:

    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        compiler_version: [ 11 ]

    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libxinerama-dev \
          libxcursor-dev \
          xorg-dev \
          libglu1-mesa-dev \
          pkg-config

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.71
          actions-cache-folder: 'emsdk-cache'

      - name: Configure and build
        run: |
          cmake . -B build -DCMAKE_TOOLCHAIN_FILE=${{env.EMSDK}}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DTHREEPP_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Release"
          cmake --build build

```

**Pull request merged**
