### PR TITLE
ImGui mouse and keyboard capture support

### PR DESCRIPTION
**Pull request by josefgraus**
I've made a small modification to Canvas::Impl and the associated CMakeLists to support ImGui mouse and keyboard capture. This allows the GUI to keep these events from propagating down to other mouse and keyboard listeners.

In effect, whenever the user selects and drags elements in an ImGui window, other controls that have registered listeners with Canvas will no longer be called. I found this to be an intuitive behavior and thought it might be a quick and useful change.

Alternatively, this behavior can be toggled with some other Canvas setting if that's preferred pretty easily.

Support for this is conditionally compiled into Canvas depending on the presence of ImGui (to be consistent with the previous optional nature of ImGui support in threepp).

### CODE REVIEW

**Comment by markaren** [comment]
I've found that linking optional libraries based on availbility leads to issues downstream, so dev branch have been updated to not link with json and curl if found. This PR would go back on that effort, unfortunantly.

The issue lies in the fact that on linux e.g., where the optional libraries might have been installed with a system manager earlier, threepp will link to it. The user then builds the library and CMake will fail not finding the an optional library becouse a find_package is missing (that is now required).

**Comment by josefgraus** [comment]
That's fair. There's often some inconsistent behavior depending on build pipeline and platform. If `find_package` fails to find imgui, the behavior wouldn't be present, but it might be counter-intuitive if imgui is indeed present just not discovered via that call.

An alternative I tinkered with in order to get mouse/keyboard capture was overriding the glfw mouse callback that Canvas::Impl registers. However the most straightforward approach would seem to require exposing the collection of registered listeners so that the application using threepp can inject the capture without losing those convenient implementations. That would also break the pimpl idiom which is so painstakingly maintained in the codebase which I felt I should avoid doing at all costs.

A third and even less desirable alternative is for me in my code to create my own derived OrbitControls that allows me to write a custom glfw mouse callback without going through Canvas.

Do you have any suggestions for a another approach I can pursue to get this functionality? My application uses a number of ImGui windows with threepp and having the events propagate to the Canvas listeners makes for a somewhat confusing control experience.

**Comment by markaren** [comment]
> Do you have any suggestions for another approach I can pursue to get this functionality? 

What I've done some far with some of the examples is: 

```cpp
// in imgui context
mouseHover = ImGui::IsWindowHovered();
// in render loop
controls.enabled = !ui.mouseHover;
```

> If find_package fails to find imgui, the behavior wouldn't be present, but it might be counter-intuitive if imgui is indeed present just not discovered via that call.

I think my explanation was off. The current issue (present on main) is that `target_link_libraries(<app> PUBLIC threepp::threepp) will fail if the system has nlohmann_json or curl installed on a system level, becouse threepp would have linked with it during build, but the current project would likely not have.

I do, however, agree that the beviour you are presenting is a wanted one. I.e. the example I made will fail if with a drop down menu, as it goes out of the "window" boundary.

**Comment by markaren** [comment]
Something, something: 

```cpp
struct IOContext {
  bool& preventMouseEvent;
  bool& preventScrollEvent;
  bool& preventKeboardEvent;
}

//

```cpp
 static void mouse_callback(GLFWwindow* w, int button, int action, int mods) {

    if (io && io->preventMouseEvent) {
     
        return;
    }
  
  auto p = static_cast<Canvas::Impl*>(glfwGetWindowUserPointer(w));
  
  auto listeners = p->mouseListeners;
  
  // ...
    }

```

**Comment by josefgraus** [comment]
> 

I think I see where you're going with this. What would you think about replacing those `bool&` in your snippet with callbacks that the user can supply? It would still allow `ImGuiIO::WantCaptureMouse` and `ImGui::WantCaptureKeyboard` to be checked directly each time an event is processed, but would remove the requirement that `Canvas.hpp` include `imgui.h` or any associated signatures? It would also generalize the capture for other future libraries that also want to adjust how input events are handled.

**Comment by josefgraus** [comment]
I pushed a change that I think is more agreeable. It removes imgui from Canvas entirely (and from the CMakeLists) and allows for user-supplied callback functions to determine when to block listeners in Canvas from receiving events.

In my projects code, I just have something like this to make all imgui windows and elements capture keyboard, mouse, and scroll events (I treat mouse and scroll events as the same category in my code but left them distinct in threepp):

```cpp
std::function<bool(void)> mouse_capture_callback = []() -> bool {
  ImGuiIO& io = ImGui::GetIO();
  return io.WantCaptureMouse;
};

std::function<bool(void)> keyboard_capture_callback = []() -> bool {
  ImGuiIO& io = ImGui::GetIO();
  return io.WantCaptureKeyboard;
};

// ...

canvas.registerMouseCapture(&mouse_capture_callback);
canvas.registerScrollCapture(&mouse_capture_callback);
canvas.registerKeyboardCapture(&keyboard_capture_callback);
```

This does exactly what I want in terms of event behavior. What do you think?

**Comment by markaren** [comment]
I think I prefer the following:

```cpp
IOCapture capture {};
capture.preventMouseEvent = [] {
    return ImGui::GetIO().WantCaptureMouse;
};
canvas.registerIOCapture(&capture);
```

How do you think?

I'll push a commit to this PR if you agree.

**Review by josefgraus — COMMENTED** [review]
Looks great. Much cleaner than what I scribbled together.

Have you gotten a chance to test out the event behavior? I was able to try it out with combo boxes that exceed the window bounds and draggable ImageButtons and it seems to work as one would expect.

**Comment by markaren** [comment]
> Have you gotten a chance to test out the event behavior?

Seems to work as expected.

**Pull request merged**
